# web port
server:
  port: ${DX_EXECUTOR_PORT:9989}
  #port: 8081

# log config
logging:
  config: classpath:logback.xml
  path: ${DX_PATH:/data}/applogs/executor/jobhandler
  #path: ./data/applogs/executor/jobhandler

datax:
  job:
    admin:
      ### datax admin address list, such as "http://address" or "http://address01,http://address02"
      #addresses: http://127.0.0.1:8080
      addresses: http://datax:${DX_SERVER_PORT:9988}
    executor:
      appname: datax-executor
      ip:
      #port: 9999
      port: ${DX_EXECUTOR_JOB_PORT:9990}
      ### job log path
      #logpath: ./data/applogs/executor/jobhandler
      logpath: ${DX_PATH:/data}/applogs/executor/jobhandler
      ### job log retention days
      logretentiondays: 30
    ### job, access token
    accessToken:

  executor:
    #jsonpath: D:\\temp\\executor\\json\\
    jsonpath: ${DX_PATH:/data}/applogs/executor/json/

  #pypath: F:\tools\datax\bin\datax.py
  pypath: ${DX_PATH:/data}/bin/datax.py